# Generated by Django 2.0.13 on 2019-04-29 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlevel',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='expired_date',
            field=models.DateField(default=datetime.date(2019, 5, 29)),
        ),
    ]
