# Generated by Django 2.0.13 on 2019-04-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190429_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='funds',
            field=models.FloatField(),
        ),
    ]
