# Generated by Django 2.0.13 on 2019-04-29 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190429_0031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.AddField(
            model_name='member',
            name='expired_date',
            field=models.DateField(default=datetime.date(2019, 5, 29)),
        ),
        migrations.AddField(
            model_name='member',
            name='funds',
            field=models.FloatField(default=0),
        ),
    ]
