# Generated by Django 2.0.13 on 2019-04-28 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLevel',
            fields=[
                ('level_status', models.CharField(choices=[('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold'), ('P', 'Platinum'), ('D', 'Diamond')], default='B', max_length=1, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='level',
            field=models.ForeignKey(default='B', on_delete=django.db.models.deletion.CASCADE, to='login.MemberLevel'),
        ),
    ]
