# Generated by Django 2.1.7 on 2019-04-15 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quesrion_text',
            new_name='question_text',
        ),
    ]
